### ISSUE TITLE
Support Python 3.13 and drop Python 3.9

### ISSUE THREAD

**Issue by tyralla** [hydpy-dev/hydpy#157]
I checked our dependencies, and we still have to wait for suitable NetCDF4 binaries (but they are already in preparation, [NetCDF4 issue 1370](https://github.com/Unidata/netcdf4-python/issues/1370)).  Hence, the following to-do list is only preliminary:

- [ ] Use the `|` operator instead of `typing.Union` (see [PEP 604](https://peps.python.org/pep-0604/)).
- [ ] Clean up ugly multi-line with statements like [this one](https://github.com/hydpy-dev/hydpy/blob/d32cc215608fb7b6b8700a4b50f6dfb237aaeb2a/hydpy/core/testtools.py#L319-L335) by using parentheses (see [Python issue 56991)](https://github.com/python/cpython/issues/56991)

**Comment by tyralla** [comment]
Proper NetCDF4 wheels are now available.  However, we must wait for Python 3.13.1 because of the bug reported [here](https://github.com/python/cpython/issues/125235).

**Comment by tyralla** [comment]
I hoped that [PEP 667](https://peps.python.org/pep-0667) would allow us to manipulate the (optimised) namespaces of functions, too, so that patterns like this became possible:

```python
from hydpy.models.hland_96 import *

simulationstep("1h")
parameterstep("1d")

def add_rconcmodel(main):
    with main.add_rconcmodel_v1("rconc_uh"):
        uh("triangle", tb=0.36728)

add_rconcmodel(model)
```

The error under Python 3.12 is: `NameError: name 'uh' is not defined`.

The (current) error under Python 3.13.0 is: `AttributeError: 'FrameLocalsProxy' object has no attribute 'pop'`.

The latter message will likely change under Python 3.13.1 due to [PR 125616](https://github.com/python/cpython/pull/125616).

However, adding and removing names from optimised scopes will still not be supported, so everything will stay as is from the user's perspective. (We might need to adapt HydPy's source code, but I expect at most minor changes.).

**Comment by tyralla** [comment]
I completed the above two tasks and a little more refurbishing (with the help of [PyUpdater](https://pypi.org/project/PyUpdater/)) and pushed everything into the branch [feature/python_3.13](https://github.com/hydpy-dev/hydpy/tree/feature/python_3.13).

That's it for now.  I will wait for Python 3.13.1, which can apparently be expected for December.

**Comment by tyralla** [comment]
[Python 3.13.1 is available now!](https://www.python.org/downloads/release/python-3131/)

**Comment by tyralla** [comment]
Hopefully, Python 3.13.1 is now well-supported.  Unfortunately, it seems not to be installed on Travis-CI so far.  Additionally, on AppVeyor, we get the following strange error:
 
```
Finished generating code
Traceback (most recent call last):
  File "C:\projects\hydpy-hep1s\prepare_build.py", line 258, in <module>
    main()  # pylint: disable=no-value-for-parameter
    ~~~~^^
  File "C:\Python313-x64\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Python313-x64\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Python313-x64\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313-x64\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\projects\hydpy-hep1s\prepare_build.py", line 251, in main
    _convert_interfaces(fast_cython=fast_cython, profile_cython=profile_cython)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\hydpy-hep1s\prepare_build.py", line 91, in _convert_interfaces
    from hydpy import config
  File "C:\projects\hydpy-hep1s\hydpy\__init__.py", line 21, in <module>
    from hydpy.core import pubtools
  File "C:\projects\hydpy-hep1s\hydpy\core\pubtools.py", line 10, in <module>
    from hydpy.core import exceptiontools
  File "C:\projects\hydpy-hep1s\hydpy\core\exceptiontools.py", line 10, in <module>
    from hydpy.core import objecttools
  File "C:\projects\hydpy-hep1s\hydpy\core\objecttools.py", line 18, in <module>
    import black
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 819, in module_from_spec
  File "<frozen importlib._bootstrap>", line 797, in _init_module_attrs
SystemError: extension module 'black' is already cached
Command exited with code 1
```

So we better wait a little longer...

**Comment by tyralla** [comment]
@holgeralbert: Travis-CI still uses Python 3.13.0 and AppVeyor an older release candidate (if I am not mistaken).  Is there something we can do?  (select another image, create a custom one, or so)

**Comment by tyralla** [comment]
The AppVeyor maintainers already responded and fixed the problem.  So, at least on AppVeyor, we can run our test suit with Python 3.13 and build the corresponding wheels for Windows.  Using Python 3.12.  instead of 3.13 on Travis CI should make no relevant difference because, besides testing, this job is only responsible for creating and deploying the online documentation.
